name: integrador2
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  intl: ^0.18.1
  flutter_localization: ^0.1.14
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.20.0
  firebase_auth: ^4.15.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\study_wave.png
    - assets\background.png
    - assets\background1.png

  fonts:
    - family: MinhaFonte
      fonts:
        - asset: fonts\Inter\static\Inter-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: fonts\Open_Sans\static\OpenSans-Medium.ttf
